### ISSUE TITLE
Separate Keycloak JS from Keycloak

### ISSUE THREAD

**Issue by jonkoops** [keycloak/keycloak-js#7]
As part of improving the Keycloak JS adapter we want to split it off from the main Keycloak project so its lifecycle can be managed separately from the rest of the projects.
```[tasklist]
### Tasks
- [ ] https://github.com/keycloak/keycloak-js/issues/5
- [ ] https://github.com/keycloak/keycloak-js/issues/2
- [ ] https://github.com/keycloak/keycloak-js/issues/4
- [ ] https://github.com/keycloak/keycloak-js/issues/31
- [ ] https://github.com/keycloak/keycloak-js/issues/3
- [ ] https://github.com/keycloak/keycloak-quickstarts/issues/652
- [ ] https://github.com/keycloak/keycloak-web/issues/553
- [ ] https://github.com/keycloak/keycloak-web/issues/565
- [ ] https://github.com/keycloak/keycloak-web/issues/554
- [ ] https://github.com/keycloak/keycloak/issues/36659
- [ ] https://github.com/keycloak/keycloak-js/issues/38
```

**Comment by jonkoops** [comment]
Closing this issue as all tasks have been completed.
